name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile Java files
        run: |
          find ./src -name "*.java" > sources.txt
          mkdir -p out
          javac -d out @sources.txt
